"""Shared numeric vocabulary: mirrors `native/mncs/memory/codes.mncs`."""

REL_UNRELATED = 0
REL_SAME = 1
REL_REFINES = 2
REL_CONTRADICTS = 3
REL_SUPERSEDES = 4
REL_AMBIGUOUS = 5
RELATIONS = {REL_UNRELATED: "UNRELATED", REL_SAME: "SAME",
             REL_REFINES: "REFINES", REL_CONTRADICTS: "CONTRADICTS",
             REL_SUPERSEDES: "SUPERSEDES", REL_AMBIGUOUS: "AMBIGUOUS"}

EV_DIRECT = 0
EV_SUPPORTED = 1
EV_WEAK = 2
EV_MISSING = 3
EVIDENCE = {EV_DIRECT: "DIRECT", EV_SUPPORTED: "SUPPORTED",
            EV_WEAK: "WEAK", EV_MISSING: "MISSING"}
EVIDENCE_SCORE = {EV_DIRECT: 100, EV_SUPPORTED: 85, EV_WEAK: 55,
                  EV_MISSING: 0}

DISP_NEW = 0
DISP_DUPLICATE = 1
DISP_REFINEMENT = 2
DISP_CONTRADICTION = 3
DISP_SUPERSESSION = 4
DISP_UNKNOWN = 5
DISPOSITIONS = {DISP_NEW: "New", DISP_DUPLICATE: "Duplicate",
                DISP_REFINEMENT: "Refinement",
                DISP_CONTRADICTION: "Contradiction",
                DISP_SUPERSESSION: "Supersession",
                DISP_UNKNOWN: "Unknown"}

STATE_CURRENT = 0
STATE_REFINED = 1
STATE_SUPERSEDED = 2
STATE_CONTRADICTED = 3
STATE_UNRESOLVED = 4
STATE_DUPLICATE = 5
STATE_UNKNOWN = 6
STATE_INVALIDATED = 7
STATES = {STATE_CURRENT: "CURRENT", STATE_REFINED: "REFINED",
          STATE_SUPERSEDED: "SUPERSEDED",
          STATE_CONTRADICTED: "CONTRADICTED",
          STATE_UNRESOLVED: "UNRESOLVED", STATE_DUPLICATE: "DUPLICATE",
          STATE_UNKNOWN: "UNKNOWN", STATE_INVALIDATED: "INVALIDATED"}

ANS_PASS = 0
ANS_UNKNOWN = 1
ANS_FAIL = 2
ANSWERS = {ANS_PASS: "PASS", ANS_UNKNOWN: "UNKNOWN", ANS_FAIL: "FAIL"}

BUDGET_FITS = 0
BUDGET_INSUFFICIENT = 1
BUDGET_UNKNOWN = 2

ESC_NONE = 0
ESC_SPECIALIST = 1
ESC_GENERAL = 2
ESC_UNKNOWN = 3

LAYER_DETERMINISTIC = 0
LAYER_TINY = 1
LAYER_SPECIALIST = 2
LAYER_LARGER = 3
LAYER_GENERAL = 4
LAYERS = {"DETERMINISTIC": LAYER_DETERMINISTIC, "TINY": LAYER_TINY,
          "SPECIALIST": LAYER_SPECIALIST, "LARGER": LAYER_LARGER,
          "GENERAL": LAYER_GENERAL}

UNC_NONE = 0
UNC_CONFLICT = 1
UNC_NO_ELIGIBLE = 2
UNC_BUDGET = 3
UNC_INSPECT = 4
UNC_STATE = 5
UNCERTAINTY = {UNC_NONE: None, UNC_CONFLICT: "unresolved-conflict",
               UNC_NO_ELIGIBLE: "no-eligible-claims",
               UNC_BUDGET: "required-information-over-budget",
               UNC_INSPECT: "deliberate-conflict-inspection",
               UNC_STATE: "unknown-state"}

RECALL_WIDTH = 64
